---
title: "Untitled"
author: "AAA"
date: "2026-06-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


if (!require("gamlss")) install.packages("gamlss")
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("lubridate")) install.packages("lubridate")

library(gamlss)
library(tidyverse)
library(lubridate)
```

## T-student or normal
In a Student-t distribution, the parameter v  small, if more than 30 is normal

```{r check-normal}
df <- read.csv("data/repeated_ids_with_countries.csv")

df <- df %>%
  mutate(
    seconds = as.numeric(hms(Official.Time)),
    minutes = seconds / 60,
    y = log(minutes),
    Sex = as.factor(M.F),
    Age = as.numeric(Age)
  ) %>%
  filter(!is.na(y)) # Remove rows with missing times

# Model 1: Normal Distribution
model_norm <- gamlss(y ~ Sex + pb(Age),
  family = NO,
  data = df,
  control = gamlss.control(n.cyc = 100)
)

# Model 2: Student-t Distribution, auto v
model_t <- gamlss(y ~ Sex + pb(Age),
  family = TF,
  data = df,
  control = gamlss.control(n.cyc = 100)
)


cat("AIC Normal:", AIC(model_norm), "\n")
cat("AIC Student-t:", AIC(model_t), "\n")

nu_val <- exp(model_t$nu.coefficients)
cat("Estimated Degrees of Freedom (nu):", nu_val, "\n")

plot(model_norm, summary = TRUE)
```
